### ISSUE TITLE
412 (Precondition Failed)

### ISSUE THREAD

**Issue by divyangdodiya** [ShankyTiwari/Real-time-private-chatting-app-using-Angular-Nodejs-mongodb-and-Socket.io#2]
Getting this error
POST http://localhost:4000/usernameAvailable 412 (Precondition Failed)
In registration page , where it check for username availability

**Comment by ShankyTiwari** [comment]
@devdodiya  It's not an error, it's a response that you are getting from Node API. Check the request of API  http://localhost:4000/usernameAvailable and make sure you are passing required parameters.

Thanks

**Comment by divyangdodiya** [comment]
I simply cloned your project and make it run , i didn't changed a single file

**Comment by divyangdodiya** [comment]
all i did is **npm install** and **ng serve** and **node server.js** command nothing else, do i've to take care of any other requirements while running on localhost ??

**Comment by ShankyTiwari** [comment]
Okay can you share the request and response for http://localhost:4000/usernameAvailable  API?

**Comment by ghoshsuman845** [comment]
![Screenshot (59)](https://user-images.githubusercontent.com/36951896/76233422-2e2e9f80-624e-11ea-8c2e-ddb6723d7c5f.png)
![Screenshot (60)](https://user-images.githubusercontent.com/36951896/76233434-338bea00-624e-11ea-96df-704edd29bf8a.png)

**Comment by ghoshsuman845** [comment]
I'm also getting the same error while clicking the registration page , please help @ShankyTiwari

**Comment by ShankyTiwari** [comment]
Hi @ghoshsuman845 have you started your MongoDB server?

**Comment by ghoshsuman845** [comment]
> Hi @ghoshsuman845 have you started your MongoDB server?

How can we connect to MongoDb Server? I have Mongo Compass in my system when I'm connecting it , its showing some error.

**Comment by ShankyTiwari** [comment]
What error you are getting?

Assuming that you are using Windows and You have installed MongoDB properly.
You can start your MongoDB server by going under this `C:\Program Files\MongoDB\Server\3.4\bin` directory. Here `3.4` is the MongoDB version it can be different.

Once you will open `bin` folder you will see the mongod file(mongod.exe), just run it. Now your MongoDB server is running.

Just in case if the above steps are not clear you can read **[this SO answer](https://stackoverflow.com/questions/20796714/how-do-i-start-mongo-db-from-windows?answertab=votes#tab-top)**, it should help.

What you should after this:
1. Create a new database, say `local`.
2. Check the `.env` file under NodeJs API and Give proper database URL. Ideally `local` should be the name of the database since I had created database with a `local` name.
3. Now run the code by `npm start`

Things should work, let me know if anything else not working!

**Comment by ghoshsuman845** [comment]
Thankyou! Everything works absolutely fine now. @ShankyTiwari
